(ns play-clj.physics-test
  (:require [clojure.test :refer :all]
            [play-clj.physics :as p]))

(deftest re-exported-function-tests
  (testing "re-exported Box2D functions exist"
    (is (resolve 'play-clj.physics/box-2d*))
    (is (resolve 'play-clj.physics/box-2d))
    (is (resolve 'play-clj.physics/box-2d!))
    (is (resolve 'play-clj.physics/body-def))
    (is (resolve 'play-clj.physics/body!))
    (is (resolve 'play-clj.physics/add-body!))
    (is (resolve 'play-clj.physics/joint-def))
    (is (resolve 'play-clj.physics/joint!))
    (is (resolve 'play-clj.physics/add-joint!))
    (is (resolve 'play-clj.physics/fixture-def))
    (is (resolve 'play-clj.physics/fixture!))
    (is (resolve 'play-clj.physics/chain-shape*))
    (is (resolve 'play-clj.physics/chain-shape))
    (is (resolve 'play-clj.physics/chain-shape!))
    (is (resolve 'play-clj.physics/circle-shape*))
    (is (resolve 'play-clj.physics/circle-shape))
    (is (resolve 'play-clj.physics/circle-shape!))
    (is (resolve 'play-clj.physics/edge-shape*))
    (is (resolve 'play-clj.physics/edge-shape))
    (is (resolve 'play-clj.physics/edge-shape!))
    (is (resolve 'play-clj.physics/polygon-shape*))
    (is (resolve 'play-clj.physics/polygon-shape))
    (is (resolve 'play-clj.physics/polygon-shape!))))

(deftest re-exported-3d-function-tests
  (testing "re-exported Bullet functions exist"
    (is (resolve 'play-clj.physics/init-bullet))
    (is (resolve 'play-clj.physics/bullet-3d*))
    (is (resolve 'play-clj.physics/bullet-3d))
    (is (resolve 'play-clj.physics/bullet-3d!))
    (is (resolve 'play-clj.physics/rigid-body*))
    (is (resolve 'play-clj.physics/rigid-body))
    (is (resolve 'play-clj.physics/rigid-body!))
    (is (resolve 'play-clj.physics/rigid-body-info))
    (is (resolve 'play-clj.physics/soft-body*))
    (is (resolve 'play-clj.physics/soft-body))
    (is (resolve 'play-clj.physics/soft-body!))
    (is (resolve 'play-clj.physics/soft-body-info))
    (is (resolve 'play-clj.physics/box-shape*))
    (is (resolve 'play-clj.physics/box-shape))
    (is (resolve 'play-clj.physics/box-shape!))
    (is (resolve 'play-clj.physics/capsule-shape*))
    (is (resolve 'play-clj.physics/capsule-shape))
    (is (resolve 'play-clj.physics/capsule-shape!))
    (is (resolve 'play-clj.physics/cone-shape*))
    (is (resolve 'play-clj.physics/cone-shape))
    (is (resolve 'play-clj.physics/cone-shape!))
    (is (resolve 'play-clj.physics/cylinder-shape*))
    (is (resolve 'play-clj.physics/cylinder-shape))
    (is (resolve 'play-clj.physics/cylinder-shape!))
    (is (resolve 'play-clj.physics/sphere-shape*))
    (is (resolve 'play-clj.physics/sphere-shape))
    (is (resolve 'play-clj.physics/sphere-shape!))))

(deftest multimethod-tests
  (testing "physics multimethods exist"
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/add-body!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/body-position!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/body-x!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/body-y!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/body-z!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/body-angle!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/first-entity))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/second-entity))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/add-joint!))))
    (is (instance? clojure.lang.MultiFn (var-get (resolve 'play-clj.physics/step!))))))
